In [1]:
import numpy as np
import scipy as cp
import sympy as sy

In [20]:
#escalar, vetor e matriz

x = 2

x2 = np.array([1,2,3])
x3 = np.array([[1],[2],[3]])
x4 = np.array([[1,2,3], [1,2,3], [1,2,3]])

In [21]:
print(x2)
print()
print(x3)
print()
print(x4)

[1 2 3]

[[1]
 [2]
 [3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [5]:
type(x)

int